CREATE TABLE TB_CLIENTE (
COD_CLIENTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
IDADE SMALLINT NOT NULL,
EMAIL VARCHAR(40) NOT NULL)

INSERT INTO TB_CLIENTE VALUES ('Jorge Alencar',40,'jorge.alencar@email.com.br')
INSERT INTO TB_CLIENTE VALUES ('Amanda Tostão',35,'amanda.tostao@email.com.br')
INSERT INTO TB_CLIENTE VALUES ('Marcelo da Silva',32,'marcelo.silva@email.com.br')

CREATE TABLE TB_PRODUTO (
COD_PRODUTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(30) NOT NULL,
VALOR DECIMAL(14,2) NOT NULL,
SITUACAO VARCHAR(1) NOT NULL)

INSERT INTO TB_PRODUTO VALUES('Fettuccine',20,'A')
INSERT INTO TB_PRODUTO VALUES('Lasanha',18,'A')
INSERT INTO TB_PRODUTO VALUES('Ravioli',21,'A')
INSERT INTO TB_PRODUTO VALUES('Risoto',20,'A')
INSERT INTO TB_PRODUTO VALUES('Nhoque ',16,'A')

CREATE TABLE TB_PEDIDO (
COD_PEDIDO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
COD_CLIENTE INT NOT NULL,
SITUACAO VARCHAR(1) NOT NULL,
DATA_PEDIDO SMALLDATETIME NOT NULL,
VALOR_TOTAL DECIMAL(14,2) NOT NULL)
ALTER TABLE TB_PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES TB_CLIENTE(COD_CLIENTE)

INSERT INTO TB_PEDIDO VALUES (1,'P',GETDATE()-1,41)
INSERT INTO TB_PEDIDO VALUES (2,'E',GETDATE()-2,20)
INSERT INTO TB_PEDIDO VALUES (3,'P',GETDATE(),16)

CREATE TABLE TB_ITEM_PEDIDO(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
COD_PEDIDO INT NOT NULL,
COD_PRODUTO INT NOT NULL,
QTD SMALLINT NOT NULL,
VALOR_UNITARIO DECIMAL(14,2)NOT NULL)
ALTER TABLE TB_ITEM_PEDIDO ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (COD_PEDIDO) REFERENCES TB_PEDIDO(COD_PEDIDO)
ALTER TABLE TB_ITEM_PEDIDO ADD CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES TB_PRODUTO(COD_PRODUTO)

INSERT INTO TB_ITEM_PEDIDO VALUES (1,1,1,20)
INSERT INTO TB_ITEM_PEDIDO VALUES (1,3,1,21)
INSERT INTO TB_ITEM_PEDIDO VALUES (2,4,1,20)
INSERT INTO TB_ITEM_PEDIDO VALUES (3,5,1,16)



SELECT * FROM TB_CLIENTE

SELECT P.COD_PEDIDO,C.NOME,P.DATA_PEDIDO,
CASE WHEN P.SITUACAO = 'P' THEN 'Pendente' ELSE 'Finalizado' END SITUACAO,
PRO.DESCRICAO,I.VALOR_UNITARIO FROM
TB_PEDIDO P
INNER JOIN TB_ITEM_PEDIDO I ON P.COD_PEDIDO = I.COD_PEDIDO
INNER JOIN TB_CLIENTE C ON P.COD_CLIENTE = C.COD_CLIENTE
INNER JOIN TB_PRODUTO PRO ON I.COD_PRODUTO = PRO.COD_PRODUTO